# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-10-24 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='country',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_title', models.CharField(default='', max_length=255)),
                ('role_description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='state',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_username', models.CharField(default='', max_length=255, unique=True)),
                ('user_password', models.CharField(default='', max_length=20)),
                ('user_name', models.CharField(default='', max_length=255)),
                ('user_email', models.EmailField(default='', max_length=255)),
                ('user_mobile', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
