# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-10-25 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.PositiveIntegerField()),
                ('CustomerName', models.CharField(max_length=100)),
                ('Carcompany', models.CharField(max_length=100)),
                ('car_type', models.CharField(max_length=100)),
                ('PhoneNumber', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(default='', max_length=255)),
                ('product_cost', models.CharField(default='', max_length=20)),
                ('product_type', models.CharField(default='', max_length=255)),
                ('product_company', models.CharField(default='', max_length=255)),
                ('product_stock', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_car_name', models.CharField(default='', max_length=255, unique=True)),
                ('order_customer_name', models.CharField(default='', max_length=255)),
                ('order_date', models.CharField(default='', max_length=255)),
                ('order_cars', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
