# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-10-24 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.PositiveIntegerField()),
                ('CustomerName', models.CharField(max_length=100)),
                ('Carcompany', models.CharField(max_length=100)),
                ('car_type', models.CharField(max_length=100)),
                ('PhoneNumber', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
    ]
