# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2023-10-24 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sales',
            fields=[
                ('sr_no', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(default='', max_length=255)),
                ('order_car_name', models.CharField(default='', max_length=255, unique=True)),
                ('order_customer_name', models.CharField(default='', max_length=255)),
                ('order_date', models.CharField(default='', max_length=255)),
                ('order_cars', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
